version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - pwd
      - cd src
      - dotnet build MyCdk
      - dotnet test MyCdk.Test --logger "trx;LogFileName=mycdk.trx"
      - cdk synth MyAppRunnerStack > my-apprunner-stack-template.yml

#reports:
#  hello-report-group:
#    files:

artifacts:
  name: aws template
  files:
    - src/my-apprunner-stack-template.yml
    - src/MyCdk.Test/TestResults/mycdk.trx
