version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - pwd
      - cd src
#      - curl artf-app-prod-9ba2c57a23df66e8.elb.ap-southeast-2.amazonaws.com
      - dotnet build MyCdk
      - dotnet test MyCdk.Test --logger "trx;LogFileName=mycdk.trx"
      - cdk synth MyAppRunnerStack > my-apprunner-stack-template.yml

reports:
  hello-report-group:
    discard-paths: yes
    file-format: VISUALSTUDIOTRX
    files:
      - src/MyCdk.Test/TestResults/mycdk.trx

artifacts:
  name: my-apprunner-stack-template.yml
  discard-paths: yes
  files:
    - src/my-apprunner-stack-template.yml
