version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - pwd
      - cd src
      - dotnet build MyCdk
      - cdk synth MyAppRunnerStack
      - dir cdk.output
  post_build:
    commands:
      - echo Saving to template to artifact S3 bucket ...
artifacts:
  name: my-apprunner-stack-template
  discard-paths: yes
  files:
    - src/my-apprunner-stack-template.yml
