version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - pwd
      - cd src
      - dotnet build MyCdk
      - dotnet test MyCdk.Test --logger "trx;LogFileName=mycdk.trx"
      - cdk synth MyAppRunnerStack > my-apprunner-stack-template.yml

reports:
  hello-report-group:
    discard-paths: yes
    file-format: VISUALSTUDIOTRX
    files:
      - src/MyCdk.Test/TestResults/mycdk.trx

artifacts:
  name: my-apprunner-stack-template
  discard-paths: yes
  files:
    - src/my-apprunner-stack-template.yml
